
		<div class="panzoom-odd">
            <div class="cut-seam-odd">
            <img class="fixed-height"src="https://ids.si.edu/ids/deliveryService?id=NPG-NPG_2002_184_p1" usemap="#page-3" />
            </div>
            
		</div>
	<map name="page-3">
    <area shape="rect" coords="115, 57, 378, 392" data-id="1" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo, reiciendis eos. Sequi nemo aut, cupiditate sunt quia quas dolor odit, libero reiciendis maiores totam numquam quaerat eius eos neque dolorum." class="tooltipLink"/>
    <area shape="rect" coords="396, 59, 665, 406" data-id="2" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores iure mollitia velit accusantium obcaecati quibusdam quo ullam ducimus nostrum consectetur incidunt, voluptatem quidem excepturi ipsam cum architecto rem autem non." class="tooltipLink"/>
    <area shape="rect" coords="682, 64, 911, 378" data-id="3" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam hic voluptates ipsa saepe repellendus dolorum error soluta architecto quod. Numquam maiores minus sapiente vitae ratione quo unde. Tempore, ab error!" class="tooltipLink"/>
    <area shape="rect" coords="927, 81, 1176, 373" data-id="4" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsam omnis corporis error similique et assumenda facilis, repellat qui. Eveniet natus necessitatibus vel recusandae sint, tempora doloribus corporis porro et dolore?" class="tooltipLink"/>
    <area shape="rect" coords="1194, 67, 1414, 379" data-id="5" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum reprehenderit temporibus sint, doloremque consectetur expedita asperiores! Asperiores suscipit aut cum eveniet dolorem laboriosam, beatae, error amet odio magnam maxime numquam." class="tooltipLink"/>
    <area shape="rect" coords="116, 407, 387, 692" data-id="6" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique eligendi odio saepe, nulla ratione nam, eveniet accusantium voluptate quia sapiente aspernatur temporibus. Accusantium recusandae inventore libero, pariatur quae vitae quis." class="tooltipLink"/>
    <area shape="rect" coords="407, 415, 656, 700" data-id="7" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas maxime fugit, dolorum magni delectus molestias voluptas, fugiat corrupti cumque architecto at placeat rerum labore perspiciatis provident est quo qui sit!" class="tooltipLink"/>
    <area shape="rect" coords="677, 394, 909, 689" data-id="8" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum deleniti minus repellendus. Officia perspiciatis dolorum a animi culpa? Sunt ipsum alias obcaecati neque deleniti debitis, expedita quos nam delectus libero." class="tooltipLink"/>
    <area shape="rect" coords="941, 388, 1182, 686" data-id="9" data-tooltip="silhouette name"  data-information="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae vero tempora dolores sequi dicta doloribus temporibus laborum voluptates eveniet minus quisquam blanditiis voluptas labore, fugiat itaque suscipit? Voluptate, earum sunt!
" class="tooltipLink"/>
    <area shape="rect" coords="1199, 388, 1415, 686" data-id="10" data-tooltip="silhouette name" data-information="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae vero tempora dolores sequi dicta doloribus temporibus laborum voluptates eveniet minus quisquam blanditiis voluptas labore, fugiat itaque suscipit? Voluptate, earum sunt!
" class="tooltipLink" />
    <area shape="rect" coords="117, 711, 413, 1013" data-id="11" data-tooltip="silhouette name" data-information="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia iste molestias sed aperiam laudantium eius aliquid a, itaque nihil modi quaerat! Et fuga consequatur consequuntur sequi perspiciatis non nam cumque." class="tooltipLink"/>
    <area shape="rect" coords="419, 725, 653, 1015" data-id="12" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dignissimos officiis similique sequi commodi aliquid nihil, assumenda modi eos possimus nostrum vitae facere iste delectus. Suscipit culpa nihil ducimus. Perspiciatis, fugit!" class="tooltipLink"/>
    <area shape="rect" coords="671, 695, 905, 1017" data-id="13" data-tooltip="silhouette name" data-information="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae vero tempora dolores sequi dicta doloribus temporibus laborum voluptates eveniet minus quisquam blanditiis voluptas labore, fugiat itaque suscipit? Voluptate, earum sunt!
" class="tooltipLink"/>
    <area shape="rect" coords="924, 690, 1172, 1010" data-id="14" data-tooltip="silhouette name" data-information="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia iste molestias sed aperiam laudantium eius aliquid a, itaque nihil modi quaerat! Et fuga consequatur consequuntur sequi perspiciatis non nam cumque." class="tooltipLink"/>
    <area shape="rect" coords="1207, 703, 1419, 999" data-id="15" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis assumenda minus expedita placeat, porro eius officia aut, eos explicabo temporibus consequatur nemo est. Debitis quis doloremque voluptates iste esse distinctio." class="tooltipLink"/>
    <area shape="rect" coords="118, 1025, 406, 1337" data-id="16" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis assumenda minus expedita placeat, porro eius officia aut, eos explicabo temporibus consequatur nemo est. Debitis quis doloremque voluptates iste esse distinctio." class="tooltipLink"/>
    <area shape="rect" coords="436, 1027, 654, 1340" data-id="17" data-tooltip="silhouette name" data-information="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt voluptatibus asperiores ea harum, voluptas voluptatum tempora et in provident inventore necessitatibus sed voluptates a perspiciatis officia est laborum molestiae. Iste." class="tooltipLink"/>
    <area shape="rect" coords="682, 1021, 909, 1319" data-id="18" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dignissimos officiis similique sequi commodi aliquid nihil, assumenda modi eos possimus nostrum vitae facere iste delectus. Suscipit culpa nihil ducimus. Perspiciatis, fugit!" class="tooltipLink"/>
    <area shape="rect" coords="915, 1013, 1173, 1318" data-id="19" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dignissimos officiis similique sequi commodi aliquid nihil, assumenda modi eos possimus nostrum vitae facere iste delectus. Suscipit culpa nihil ducimus. Perspiciatis, fugit!" class="tooltipLink"/>
    <area shape="rect" coords="1195, 1016, 1416, 1307" data-id="20" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dignissimos officiis similique sequi commodi aliquid nihil, assumenda modi eos possimus nostrum vitae facere iste delectus. Suscipit culpa nihil ducimus. Perspiciatis, fugit!" class="tooltipLink"/>
    <area shape="rect" coords="119, 1347, 410, 1652" data-id=21 data-tooltip="silhouette name" data-information="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae vero tempora dolores sequi dicta doloribus temporibus laborum voluptates eveniet minus quisquam blanditiis voluptas labore, fugiat itaque suscipit? Voluptate, earum sunt!
" class="tooltipLink"/>
    <area shape="rect" coords="415, 1351, 650, 1648" data-id="22" data-tooltip="silhouette name" data-information="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt voluptatibus asperiores ea harum, voluptas voluptatum tempora et in provident inventore necessitatibus sed voluptates a perspiciatis officia est laborum molestiae. Iste." class="tooltipLink"/>
    <area shape="rect" coords="678, 1331, 916, 1634" data-id="23" data-tooltip="silhouette name" data-information="" class="tooltipLink"/>
    <area shape="rect" coords="933, 1329, 1170, 1631" data-id="24" data-tooltip="silhouette name" data-information="Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt voluptatibus asperiores ea harum, voluptas voluptatum tempora et in provident inventore necessitatibus sed voluptates a perspiciatis officia est laborum molestiae. Iste." class="tooltipLink"/>
    <area shape="rect" coords="1194, 1324, 1416, 1630" data-id="25" data-tooltip="silhouette name" data-information="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae vero tempora dolores sequi dicta doloribus temporibus laborum voluptates eveniet minus quisquam blanditiis voluptas labore, fugiat itaque suscipit? Voluptate, earum sunt!
" class="tooltipLink"/>
    <area shape="rect" coords="120, 1659, 411, 1973" data-id="26" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis assumenda minus expedita placeat, porro eius officia aut, eos explicabo temporibus consequatur nemo est. Debitis quis doloremque voluptates iste esse distinctio." class="tooltipLink" />
    <area shape="rect" coords="431, 1657, 649, 1962" data-id="27" data-tooltip="silhouette name" data-information="" class="tooltipLink"/>
    <area shape="rect" coords="675, 1642, 918, 1950" data-id="28" data-tooltip="silhouette name" data-information="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia iste molestias sed aperiam laudantium eius aliquid a, itaque nihil modi quaerat! Et fuga consequatur consequuntur sequi perspiciatis non nam cumque." class="tooltipLink"/>
    <area shape="rect" coords="931, 1641, 1174, 1943" data-id="29" data-tooltip="silhouette name" data-information="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dignissimos officiis similique sequi commodi aliquid nihil, assumenda modi eos possimus nostrum vitae facere iste delectus. Suscipit culpa nihil ducimus. Perspiciatis, fugit!" class="tooltipLink" />
    <area shape="rect" coords="1189, 1644, 1420, 1937" data-id="30" data-tooltip="silhouette name" data-information="Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae vero tempora dolores sequi dicta doloribus temporibus laborum voluptates eveniet minus quisquam blanditiis voluptas labore, fugiat itaque suscipit? Voluptate, earum sunt!
" class="tooltipLink" />
</map>
